In [9]:
#import libraries
import pandas as pd
import numpy as np

#load csv file data with headers

location = "datasets/DC_Properties.csv"
df = pd.read_csv(location)
df.head(158957)

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (18,19,20,21,22,23,24,33,34,35,37,43,45) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
0,0,4,0,Warm Cool,Y,2.0,8,4,1910.0,1988.0,...,-77.040832,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
1,1,3,1,Warm Cool,Y,2.0,11,5,1898.0,2007.0,...,-77.040764,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
2,2,3,1,Hot Water Rad,Y,2.0,9,5,1910.0,2009.0,...,-77.040678,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
3,3,3,1,Hot Water Rad,Y,2.0,8,5,1900.0,2003.0,...,-77.040629,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
4,4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,...,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
5,5,3,2,Hot Water Rad,Y,1.0,10,5,1913.0,NaN,...,-77.039715,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
6,6,1,0,Warm Cool,Y,2.0,5,2,1917.0,1988.0,...,-77.041055,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
7,7,3,1,Hot Water Rad,Y,2.0,8,4,1906.0,2011.0,...,-77.040129,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
8,8,3,1,Warm Cool,Y,2.0,7,3,1908.0,2008.0,...,-77.039903,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
9,9,1,1,Hot Water Rad,Y,1.0,6,2,1908.0,1979.0,...,-77.040081,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
10,10,3,0,Forced Air,N,3.0,12,5,1890.0,1950.0,...,-77.040760,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
11,11,5,0,Hot Water Rad,Y,3.0,16,6,1905.0,NaN,...,-77.039718,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
12,12,2,0,Hot Water Rad,N,2.0,9,5,1894.0,1979.0,...,-77.039569,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
13,13,2,0,Warm Cool,Y,2.0,11,5,1885.0,1979.0,...,-77.039644,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
14,14,3,1,Warm Cool,Y,2.0,5,3,1917.0,2000.0,...,-77.039716,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
15,15,2,1,Warm Cool,Y,2.0,9,4,1908.0,1990.0,...,-77.039784,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
16,16,3,1,Warm Cool,Y,1.0,8,3,1908.0,2006.0,...,-77.039844,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
17,17,2,0,Hot Water Rad,N,1.0,6,3,1908.0,1987.0,...,-77.039961,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
18,18,3,1,Hot Water Rad,Y,2.0,10,4,1908.0,2006.0,...,-77.040020,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
19,19,3,1,Hot Water Rad,Y,2.0,9,3,1908.0,2013.0,...,-77.040138,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
20,20,3,1,Hot Water Rad,Y,1.0,14,5,1880.0,2009.0,...,-77.033774,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
21,21,3,0,Forced Air,Y,2.0,12,3,1880.0,2009.0,...,-77.033838,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
22,22,1,0,Forced Air,Y,1.0,6,3,1880.0,2010.0,...,-77.033925,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
23,23,2,1,Forced Air,Y,1.0,5,3,1880.0,2010.0,...,-77.033972,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
24,24,2,1,Hot Water Rad,Y,1.0,8,3,1880.0,2004.0,...,-77.034070,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
25,25,1,0,Hot Water Rad,N,1.0,8,4,1880.0,2010.0,...,-77.034156,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
26,26,1,0,Hot Water Rad,N,1.0,10,5,1900.0,2004.0,...,-77.034258,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
27,27,3,0,Hot Water Rad,Y,4.0,9,3,1900.0,1963.0,...,-77.034182,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
28,28,3,0,Warm Cool,Y,2.0,10,4,1900.0,1960.0,...,-77.034119,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
29,29,3,1,Forced Air,Y,2.0,11,3,1900.0,2014.0,...,-77.034051,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158927,158927,2,0,Ht Pump,Y,NaN,6,3,1993.0,1993.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158928,158928,2,1,Ht Pump,Y,NaN,5,2,2013.0,NaN,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158929,158929,2,1,Ht Pump,Y,NaN,5,2,2013.0,NaN,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158930,158930,2,0,Forced Air,N,NaN,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158931,158931,2,1,Forced Air,N,NaN,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158932,158932,2,1,Forced Air,N,NaN,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158933,158933,2,0,Ht Pump,Y,NaN,4,2,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158934,158934,1,1,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158935,158935,1,0,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158936,158936,1,0,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158937,158937,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158938,158938,2,0,Warm Cool,Y,NaN,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158939,158939,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158940,158940,2,0,Forced Air,Y,NaN,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158941,158941,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158942,158942,2,0,Forced Air,Y,NaN,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158943,158943,2,1,Forced Air,Y,NaN,5,2,2004.0,2004.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158944,158944,2,1,Forced Air,Y,NaN,5,2,2004.0,2004.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158945,158945,1,0,Forced Air,Y,NaN,3,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158946,158946,1,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158947,158947,2,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158948,158948,2,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158949,158949,1,1,Forced Air,Y,NaN,4,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158950,158950,3,0,Forced Air,Y,NaN,5,3,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158951,158951,3,1,Forced Air,Y,NaN,5,3,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158952,158952,1,0,Forced Air,Y,NaN,3,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158953,158953,1,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158954,158954,2,0,Forced Air,Y,NaN,4,2,1920.0,2007.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158955,158955,1,0,Warm Cool,Y,NaN,2,0,1965.0,NaN,...,-77.018230,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,504,-77.018232,38.872961,SW
158956,158956,1,0,Warm Cool,Y,NaN,2,0,1965.0,NaN,...,-77.018230,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,504,-77.018232,38.872961,SW

In [10]:
df.shape

(158957, 49)

In [12]:
#show the data type of each column
df.dtypes

Unnamed: 0              int64
BATHRM                  int64
HF_BATHRM               int64
HEAT                   object
AC                     object
NUM_UNITS             float64
ROOMS                   int64
BEDRM                   int64
AYB                   float64
YR_RMDL               float64
EYB                     int64
STORIES               float64
SALEDATE               object
PRICE                 float64
QUALIFIED              object
SALE_NUM                int64
GBA                   float64
BLDG_NUM                int64
STYLE                  object
STRUCT                 object
GRADE                  object
CNDTN                  object
EXTWALL                object
ROOF                   object
INTWALL                object
KITCHENS              float64
FIREPLACES              int64
USECODE                 int64
LANDAREA                int64
GIS_LAST_MOD_DTTM      object
SOURCE                 object
CMPLX_NUM             float64
LIVING_GBA            float64
FULLADDRESS            object
CITY                   object
STATE                  object
ZIPCODE               float64
NATIONALGRID           object
LATITUDE              float64
LONGITUDE             float64
ASSESSMENT_NBHD        object
ASSESSMENT_SUBNBHD     object
CENSUS_TRACT          float64
CENSUS_BLOCK           object
WARD                   object
SQUARE                 object
X                     float64
Y                     float64
QUADRANT               object
dtype: object

In [13]:
df.describe()

,Unnamed: 0,BATHRM,HF_BATHRM,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,EYB,STORIES,...,USECODE,LANDAREA,CMPLX_NUM,LIVING_GBA,ZIPCODE,LATITUDE,LONGITUDE,CENSUS_TRACT,X,Y
count,158957.000000,158957.000000,158957.000000,106696.000000,158957.000000,158957.000000,158686.000000,80928.000000,158957.000000,106652.000000,...,158957.000000,158957.000000,52261.000000,52261.000000,158956.000000,158956.000000,158956.000000,158956.000000,158720.000000,158720.000000
mean,79478.000000,1.810678,0.458237,1.198039,6.187736,2.732506,1941.987579,1998.243537,1963.718024,2.091793,...,14.252999,2473.282158,2371.544249,888.834542,20012.694563,38.914854,-77.016676,5348.216324,-77.016712,38.914846
std,45887.077707,0.976396,0.587571,0.596924,2.618165,1.358864,33.640234,16.575786,24.923150,2.933323,...,3.725736,5059.046023,1114.272364,420.185822,15.627084,0.031723,0.040938,3369.645953,0.040933,0.031682
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1754.000000,20.000000,1800.000000,0.000000,...,11.000000,0.000000,1001.000000,0.000000,20001.000000,38.819731,-77.113909,100.000000,-77.113135,38.820576
25%,39739.000000,1.000000,0.000000,1.000000,4.000000,2.000000,1918.000000,1985.000000,1954.000000,2.000000,...,11.000000,697.000000,1501.000000,616.000000,20007.000000,38.895425,-77.042892,2102.000000,-77.042894,38.895432
50%,79478.000000,2.000000,0.000000,1.000000,6.000000,3.000000,1937.000000,2004.000000,1963.000000,2.000000,...,13.000000,1649.000000,2265.000000,783.000000,20011.000000,38.915337,-77.019596,5201.000000,-77.019581,38.915229
75%,119217.000000,2.000000,1.000000,1.000000,7.000000,3.000000,1960.000000,2010.000000,1975.000000,2.000000,...,17.000000,3000.000000,2910.000000,1060.000000,20018.000000,38.936075,-76.988626,8302.000000,-76.988842,38.936077
max,158956.000000,14.000000,11.000000,6.000000,48.000000,24.000000,2019.000000,2019.000000,2018.000000,826.000000,...,117.000000,942632.000000,5621.000000,8553.000000,20392.000000,38.995540,-76.909758,11100.000000,-76.910511,38.993646

In [21]:

df=pd.DataFrame(data=df, columns=['QUADRANT', 'PRICE','BEDRM', 'BATHRM', 'HF_BATHRM', 'CNDTN', 'AYB'])
df

       QUADRANT      PRICE  BEDRM  BATHRM  HF_BATHRM      CNDTN     AYB
0            NW  1095000.0      4       4          0       Good  1910.0
1            NW        NaN      5       3          1       Good  1898.0
2            NW  2100000.0      5       3          1  Very Good  1910.0
3            NW  1602000.0      5       3          1       Good  1900.0
4            NW        NaN      3       2          1       Good  1913.0
5            NW  1950000.0      5       3          2       Good  1913.0
6            NW        NaN      2       1          0    Average  1917.0
7            NW  1050000.0      4       3          1    Average  1906.0
8            NW  1430000.0      3       3          1  Very Good  1908.0
9            NW        NaN      2       1          1    Average  1908.0
10           NW        NaN      5       3          0       Fair  1890.0
11           NW        NaN      6       5          0    Average  1905.0
12           NW        NaN      5       2          0    Average  1894.0
13           NW        NaN      5       2          0    Average  1885.0
14           NW  1325000.0      3       3          1  Very Good  1917.0
15           NW        NaN      4       2          1    Average  1908.0
16           NW  1240000.0      3       3          1  Very Good  1908.0
17           NW        NaN      3       2          0    Average  1908.0
18           NW        NaN      4       3          1       Good  1908.0
19           NW   592250.0      3       3          1       Good  1908.0
20           NW    33232.0      5       3          1  Very Good  1880.0
21           NW        NaN      3       3          0       Good  1880.0
22           NW   907400.0      3       1          0       Good  1880.0
23           NW  1065000.0      3       2          1  Very Good  1880.0
24           NW  1100000.0      3       2          1       Good  1880.0
25           NW    20000.0      4       1          0       Good  1880.0
26           NW        NaN      5       1          0    Average  1900.0
27           NW   703700.0      3       3          0    Average  1900.0
28           NW        NaN      4       3          0    Average  1900.0
29           NW  1210000.0      3       3          1  Very Good  1900.0
...         ...        ...    ...     ...        ...        ...     ...
158927       NW        NaN      3       2          0        NaN  1993.0
158928       NW   632400.0      2       2          1        NaN  2013.0
158929       NW   574000.0      2       2          1        NaN  2013.0
158930       NW   365000.0      2       2          0        NaN  1900.0
158931       NW   405000.0      2       2          1        NaN  1900.0
158932       NW   505000.0      2       2          1        NaN  1900.0
158933       NW   520000.0      2       2          0        NaN  1880.0
158934       NW   499900.0      1       1          1        NaN  1880.0
158935       NW   451000.0      1       1          0        NaN  1880.0
158936       NW   564900.0      1       1          0        NaN  1880.0
158937       NW        NaN      2       1          0        NaN  1992.0
158938       NW   660000.0      4       2          0        NaN  1992.0
158939       NW   380000.0      2       1          0        NaN  1992.0
158940       NW        NaN      4       2          0        NaN  1992.0
158941       NW        NaN      2       1          0        NaN  1992.0
158942       NW        NaN      4       2          0        NaN  1992.0
158943       NW   539000.0      2       2          1        NaN  2004.0
158944       NW   908500.0      2       2          1        NaN  2004.0
158945       NW   450000.0      1       1          0        NaN  1938.0
158946       NW   485355.0      2       1          0        NaN  1938.0
158947       NW   320000.0      2       2          0        NaN  1938.0
158948       NW   460000.0      2       2          0        NaN  1938.0
158949       NW   550000.0      1       1          1        NaN  1938.0
158950       NW   635000.0      3       3          0        NaN  1938.0
158951       NW   389000.0      3       3          1        NaN  1938.0
158952       NW   399900.0      1       1          0        NaN  1938.0
158953       NW   416000.0      2       1          0        NaN  1938.0
158954       NW   600000.0      2       2          0        NaN  1920.0
158955       SW   215100.0      0       1          0        NaN  1965.0
158956       SW        NaN      0       1          0        NaN  1965.0

[158957 rows x 7 columns]

In [30]:


df_NE=pd.DataFrame(data=df, columns=['QUADRANT', 'PRICE','BEDRM', 'BATHRM', 'HF_BATHRM', 'CNDTN', 'AYB'])

df.loc[df['QUADRANT'] == 'NE'] #finds rows where the QUADRANT is NE

       QUADRANT      PRICE  BEDRM  BATHRM  HF_BATHRM      CNDTN     AYB
3627         NE        NaN      4       4          0    Average  1915.0
3628         NE  1700000.0      4       3          0  Very Good  1890.0
3629         NE        NaN      3       3          0       Good  1890.0
3630         NE   777000.0      2       1          1       Good  1880.0
3631         NE        NaN      3       3          1       Good  1890.0
3632         NE        NaN      4       2          1       Good  1890.0
3633         NE        NaN      3       3          0    Average  1890.0
3634         NE   220000.0      4       2          1    Average  1899.0
3635         NE        NaN      3       2          1    Average  1890.0
3636         NE   750000.0      2       3          2       Good  1890.0
3637         NE  1500000.0      3       2          2  Very Good  1890.0
3638         NE        NaN      2       2          0       Good  1890.0
3665         NE  1100000.0      3       2          1  Very Good  1914.0
3666         NE   997000.0      4       3          1       Good  1914.0
3667         NE  1030000.0      4       3          1       Good  1941.0
3668         NE   935100.0      4       3          1    Average  1988.0
3669         NE        NaN      4       3          1       Good  1988.0
3670         NE        NaN      4       3          1       Good  1988.0
3671         NE   814777.0      4       3          1       Good  1988.0
3672         NE   850000.0      4       3          1       Good  1988.0
3673         NE   675000.0      3       2          0       Good  1905.0
3674         NE   921000.0      3       2          1       Good  1905.0
3747         NE        NaN      5       4          0    Average  1880.0
3748         NE  1500000.0      4       4          1       Good  1905.0
3749         NE        NaN      4       3          0       Good  1907.0
3750         NE        NaN      5       3          0    Average  1907.0
3751         NE  1050000.0      3       3          0    Average  1906.0
3752         NE  1020000.0      4       2          1       Good  1907.0
3753         NE   962000.0      6       4          1       Good  1907.0
3754         NE        NaN      3       3          1    Average  1908.0
...         ...        ...    ...     ...        ...        ...     ...
154384       NE        NaN      1       1          0        NaN  1908.0
154385       NE        NaN      1       1          0        NaN  1908.0
154386       NE   399999.0      1       1          0        NaN  1908.0
154387       NE        NaN      1       1          0        NaN  1908.0
154388       NE   437000.0      1       1          0        NaN  1908.0
154389       NE    96000.0      1       1          0        NaN  1908.0
154390       NE   409000.0      1       1          0        NaN  1908.0
154391       NE        NaN      1       1          0        NaN  1908.0
154392       NE   393000.0      1       1          0        NaN  1908.0
154393       NE    99000.0      0       1          0        NaN  1927.0
154394       NE   103000.0      0       1          0        NaN  1927.0
154395       NE   270000.0      1       1          0        NaN  1927.0
154396       NE   176500.0      0       1          0        NaN  1927.0
154397       NE    92000.0      0       1          0        NaN  1927.0
154398       NE    42000.0      1       1          0        NaN  1927.0
154399       NE   206000.0      1       1          0        NaN  1927.0
154400       NE   324999.0      1       1          0        NaN  1927.0
154401       NE        NaN      1       1          0        NaN  1927.0
154402       NE    48950.0      1       1          0        NaN  1927.0
154403       NE        NaN      1       1          0        NaN  1927.0
154404       NE        NaN      0       1          0        NaN  1927.0
154405       NE    31500.0      1       1          0        NaN  1927.0
154406       NE   182000.0      1       1          0        NaN  1927.0
154407       NE        NaN      1       1          0        NaN  1927.0
154408       NE   295000.0      1       1          0        NaN  1927.0
154409       NE   135000.0      1       1          0        NaN  1927.0
154410       NE   320000.0      1       1          0        NaN  1927.0
154411       NE   360000.0      1       1          0        NaN  1927.0
154412       NE    49900.0      1       1          0        NaN  1927.0
158735       NE   390000.0      1       1          0        NaN  2015.0

[37675 rows x 7 columns]